name: Stale

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          operations-per-run: 250

          stale-issue-message: "This issue has been marked as stale because there has been no activity in the past 6 months. Please add a comment to keep it open."
          stale-issue-label: stale
          days-before-issue-stale: 180
          days-before-issue-close: 30

          stale-pr-message: "This PR has been marked as stale because there has been no activity in the past 6 months. Please add a comment to keep it open. Thank you for your contribution."
          stale-pr-label: stale
          days-before-pr-stale: 180
          days-before-pr-close: 30
          delete-branch: true
